require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'labtest' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # The following line uses react-native-restart, linking with
  # the library and setting the Header Search Paths for you
  pod 'react-native-restart', :path => '../node_modules/react-native-restart'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'react-native-restart', :path => '../node_modules/react-native-restart'

  pod 'RNExitApp', :path => '../node_modules/react-native-exit-app'

  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

  target 'labtestTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'labtest-tvOS' do
  # Pods for labtest-tvOS

  target 'labtest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
